/*INSERT INTO [Role] (name) VALUES 
('Usuario'),('Administrador');*/

INSERT INTO [User] (username,name,pass,mail,role_id) VALUES
('username1','Usuario1','123456','correo1@mail.cl',2),
('username2','Usuario2','123456','correo2@mail.cl',1),
('username3','Usuario3','123456','correo3@mail.cl',2),
('username4','Usuario4','123456','correo4@mail.cl',1),
('username5','Usuario5','123456','correo5@mail.cl',1);

INSERT INTO [Multimedia] (url) VALUES 
('http://lorempixel.com/450/450/nature/'),
('http://lorempixel.com/450/450/cat/'),
('http://lorempixel.com/450/450/nightlife/'),
('https://images.reporteindigo.com/wp-content/uploads/2017/09/920_adiostvanaloga_22.jpg');--id 4 televison

INSERT INTO [Publication] (title,content,multimedia_id,user_id) VALUES
('Titulo publicacion','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend at ante nec cursus. Quisque mattis risus sed luctus fringilla. Ut commodo ipsum sed mi facilisis, vel condimentum tellus suscipit. Donec fringilla tortor sem. Aliquam erat volutpat. Sed ut erat fermentum ligula mollis vestibulum. Morbi ultrices ac nisi ac congue. Suspendisse non sem sed tortor posuere rhoncus. Fusce nec gravida nulla. Donec pretium auctor tortor sit amet iaculis. Nullam rhoncus mi quis convallis ultricies. Morbi vel dapibus est, eget iaculis urna. Duis sit amet diam vel sapien vestibulum malesuada.\nPraesent mi nisl, pellentesque et elit id, placerat scelerisque ex. Vivamus fermentum nisi at mauris scelerisque blandit. Donec magna felis, malesuada nec bibendum a, commodo in est. Suspendisse aliquam sapien fermentum quam lacinia, non dictum mi dictum. Maecenas sollicitudin dolor purus, vel laoreet nibh ullamcorper in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ac porta quam, id posuere magna. Duis vitae est molestie, auctor est eu, feugiat risus. Aenean a enim blandit, sagittis diam vitae, consectetur orci.\nNulla consequat mi quis arcu mollis sodales. Maecenas sed mattis nisl, at blandit sapien. Aenean nibh arcu, aliquet nec malesuada ut, porttitor id neque. Vivamus volutpat sapien nunc, nec elementum mi rutrum vitae. Maecenas elit eros, vehicula quis viverra eu, tincidunt eget ligula. Maecenas interdum, justo quis commodo suscipit, turpis leo rutrum mi, sit amet aliquam ligula libero at erat. Nam magna metus, ullamcorper ut sodales eu, placerat id lectus. Praesent sit amet ligula efficitur, ornare lectus aliquet, tincidunt orci.\nDuis feugiat tempor arcu, sit amet tincidunt neque. Pellentesque laoreet risus nec turpis semper ultricies. Sed dapibus mauris dui, at sollicitudin nisi cursus a. Aenean quis dignissim odio, in rhoncus sapien. Vivamus porttitor accumsan ligula, eget placerat nisi vulputate sed. Fusce cursus pharetra diam, id rhoncus est faucibus vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris eget gravida eros. Maecenas elementum mattis libero a rutrum. Maecenas dictum dui pretium tincidunt luctus. Duis quis sagittis elit, ut scelerisque sem. Integer et sapien tortor. Suspendisse arcu neque, blandit eget sodales non, tristique ut mauris. Praesent in massa ut sem sollicitudin lacinia.',1,2),
('Titulo publicacion','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend at ante nec cursus. Quisque mattis risus sed luctus fringilla. Ut commodo ipsum sed mi facilisis, vel condimentum tellus suscipit. Donec fringilla tortor sem. Aliquam erat volutpat. Sed ut erat fermentum ligula mollis vestibulum. Morbi ultrices ac nisi ac congue. Suspendisse non sem sed tortor posuere rhoncus. Fusce nec gravida nulla. Donec pretium auctor tortor sit amet iaculis. Nullam rhoncus mi quis convallis ultricies. Morbi vel dapibus est, eget iaculis urna. Duis sit amet diam vel sapien vestibulum malesuada.\nPraesent mi nisl, pellentesque et elit id, placerat scelerisque ex. Vivamus fermentum nisi at mauris scelerisque blandit. Donec magna felis, malesuada nec bibendum a, commodo in est. Suspendisse aliquam sapien fermentum quam lacinia, non dictum mi dictum. Maecenas sollicitudin dolor purus, vel laoreet nibh ullamcorper in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ac porta quam, id posuere magna. Duis vitae est molestie, auctor est eu, feugiat risus. Aenean a enim blandit, sagittis diam vitae, consectetur orci.\nNulla consequat mi quis arcu mollis sodales. Maecenas sed mattis nisl, at blandit sapien. Aenean nibh arcu, aliquet nec malesuada ut, porttitor id neque. Vivamus volutpat sapien nunc, nec elementum mi rutrum vitae. Maecenas elit eros, vehicula quis viverra eu, tincidunt eget ligula. Maecenas interdum, justo quis commodo suscipit, turpis leo rutrum mi, sit amet aliquam ligula libero at erat. Nam magna metus, ullamcorper ut sodales eu, placerat id lectus. Praesent sit amet ligula efficitur, ornare lectus aliquet, tincidunt orci.\nDuis feugiat tempor arcu, sit amet tincidunt neque. Pellentesque laoreet risus nec turpis semper ultricies. Sed dapibus mauris dui, at sollicitudin nisi cursus a. Aenean quis dignissim odio, in rhoncus sapien. Vivamus porttitor accumsan ligula, eget placerat nisi vulputate sed. Fusce cursus pharetra diam, id rhoncus est faucibus vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris eget gravida eros. Maecenas elementum mattis libero a rutrum. Maecenas dictum dui pretium tincidunt luctus. Duis quis sagittis elit, ut scelerisque sem. Integer et sapien tortor. Suspendisse arcu neque, blandit eget sodales non, tristique ut mauris. Praesent in massa ut sem sollicitudin lacinia.',2,1),
('Titulo publicacion','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend at ante nec cursus. Quisque mattis risus sed luctus fringilla. Ut commodo ipsum sed mi facilisis, vel condimentum tellus suscipit. Donec fringilla tortor sem. Aliquam erat volutpat. Sed ut erat fermentum ligula mollis vestibulum. Morbi ultrices ac nisi ac congue. Suspendisse non sem sed tortor posuere rhoncus. Fusce nec gravida nulla. Donec pretium auctor tortor sit amet iaculis. Nullam rhoncus mi quis convallis ultricies. Morbi vel dapibus est, eget iaculis urna. Duis sit amet diam vel sapien vestibulum malesuada.\nPraesent mi nisl, pellentesque et elit id, placerat scelerisque ex. Vivamus fermentum nisi at mauris scelerisque blandit. Donec magna felis, malesuada nec bibendum a, commodo in est. Suspendisse aliquam sapien fermentum quam lacinia, non dictum mi dictum. Maecenas sollicitudin dolor purus, vel laoreet nibh ullamcorper in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ac porta quam, id posuere magna. Duis vitae est molestie, auctor est eu, feugiat risus. Aenean a enim blandit, sagittis diam vitae, consectetur orci.\nNulla consequat mi quis arcu mollis sodales. Maecenas sed mattis nisl, at blandit sapien. Aenean nibh arcu, aliquet nec malesuada ut, porttitor id neque. Vivamus volutpat sapien nunc, nec elementum mi rutrum vitae. Maecenas elit eros, vehicula quis viverra eu, tincidunt eget ligula. Maecenas interdum, justo quis commodo suscipit, turpis leo rutrum mi, sit amet aliquam ligula libero at erat. Nam magna metus, ullamcorper ut sodales eu, placerat id lectus. Praesent sit amet ligula efficitur, ornare lectus aliquet, tincidunt orci.\nDuis feugiat tempor arcu, sit amet tincidunt neque. Pellentesque laoreet risus nec turpis semper ultricies. Sed dapibus mauris dui, at sollicitudin nisi cursus a. Aenean quis dignissim odio, in rhoncus sapien. Vivamus porttitor accumsan ligula, eget placerat nisi vulputate sed. Fusce cursus pharetra diam, id rhoncus est faucibus vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris eget gravida eros. Maecenas elementum mattis libero a rutrum. Maecenas dictum dui pretium tincidunt luctus. Duis quis sagittis elit, ut scelerisque sem. Integer et sapien tortor. Suspendisse arcu neque, blandit eget sodales non, tristique ut mauris. Praesent in massa ut sem sollicitudin lacinia.',3,4);

--PRODUCTOS

INSERT INTO [ExchangeMode] (name) VALUES 
('Regalo'),
('Trueque');