//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoStand.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int chat_id { get; set; }
        public string content { get; set; }
        public System.DateTime send_on { get; set; }
        public Nullable<int> multimedia_id { get; set; }
        public bool status { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Multimedia Multimedia { get; set; }
        public virtual User User { get; set; }
    }
}
