//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoStand.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public int reportType_id { get; set; }
        public int role_id { get; set; }
        public int reportingUser_id { get; set; }
        public Nullable<int> reportedUser_id { get; set; }
        public Nullable<int> reportedPublication_id { get; set; }
        public Nullable<int> reportedComment_id { get; set; }
        public Nullable<int> reportedProduct_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Product Product { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
